apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxold
          image: nginx:latest
          volumeMounts:
            - name: myemptydir
              mountPath: /etc/myemptydir
        - name: bash-container
          image: busybox:latest  
          command: [ "sleep", "3600" ] 
          volumeMounts:
            - mountPath: /tmp/myemptydir 
              name: myemptydir
      volumes:
        - name: myemptydir
          emptyDir: {}
