apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    hostPath:
      path: /tmp/hostpath-data
      type: DirectoryOrCreate
